export { HeroSection } from "./components/HeroSection";
export { MarqueeTicker } from "./components/MarqueeTicker";
export { MomentoAtualSection } from "./components/MomentoAtualSection";
export { EcossistemaSection } from "./components/EcossistemaSection";
export { FeatureTabsSection } from "./components/FeatureTabsSection";
export { JornadaSection } from "./components/JornadaSection";
export { InvestimentoSection } from "./components/InvestimentoSection";
export { PrecosSection } from "./components/PrecosSection";
export { ContinuidadeSection } from "./components/ContinuidadeSection";
export { CTASection } from "./components/CTASection";
export type * from "./types";
